site_name: SatGS
repo_url: https://github.com/DB8LE/satgs
edit_uri: edit/main/docs/

nav:
  - "Home": "index.md"
  - "Interfaces": "interfaces.md"
  - "North- and Southcrossings": "crossings.md"
  - "Example Setup": "example.md"

theme:
  name: readthedocs
  highlightjs: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

markdown_extensions:
  - admonition
