name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/satgs
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Configure and Build
        run: |
          poetry config virtualenvs.create false
          poetry install --sync --no-interaction
          poetry build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1